/**
 * 原神武器相关数据，由多数据源整合
 */

const weapons = [
  "alley-hunter",
  "amber-catalyst",
  "amenoma-kageuchi",
  "amos-bow",
  "apprentice-s-notes",
  "aquila-favonia",
  "beginner-s-protector",
  "black-tassel",
  "blackcliff-amulet",
  "blackcliff-longsword",
  "blackcliff-pole",
  "blackcliff-slasher",
  "blackcliff-warbow",
  "bloodtainted-greatsword",
  "compound-bow",
  "cool-steel",
  "crescent-pike",
  "dark-iron-sword",
  "deathmatch",
  "debate-club",
  "dodoco-tales",
  "dragon-s-bane",
  "dragonspine-spear",
  "dull-blade",
  "ebony-bow",
  "elegy-for-the-end",
  "emerald-orb",
  "engulfing-lightning",
  "everlasting-moonglow",
  "eye-of-perception",
  "favonius-codex",
  "favonius-greatsword",
  "favonius-lance",
  "favonius-sword",
  "favonius-warbow",
  "ferrous-shadow",
  "festering-desire",
  "fillet-blade",
  "freedom-sworn",
  "frostbearer",
  "hakushin-ring",
  "halberd",
  "hamayumi",
  "harbinger-of-dawn",
  "hunter-s-bow",
  "iron-point",
  "iron-sting",
  "kaguras-verity",
  "katsuragikiri-nagamasa",
  "kitain-cross-spear",
  "lion-s-roar",
  "lithic-blade",
  "lithic-spear",
  "lost-prayer-to-the-sacred-winds",
  "luxurious-sea-lord",
  "magic-guide",
  "mappa-mare",
  "memory-of-dust",
  "messenger",
  "mistsplitter-reforged",
  "mitternachts-waltz",
  "old-merc-s-pal",
  "otherworldly-story",
  "pocket-grimoire",
  "predator",
  "primordial-jade-cutter",
  "primordial-jade-winged-spear",
  "prototype-archaic",
  "prototype-crescent",
  "prototype-grudge",
  "prototype-malice",
  "prototype-rancour",
  "quartz",
  "rainslasher",
  "raven-bow",
  "recurve-bow",
  "royal-bow",
  "royal-greatsword",
  "royal-grimoire",
  "royal-longsword",
  "royal-spear",
  "rust",
  "sacrificial-bow",
  "sacrificial-fragments",
  "sacrificial-greatsword",
  "sacrificial-sword",
  "seasoned-hunter-s-bow",
  "serpent-spine",
  "sharpshooter-s-oath",
  "silver-sword",
  "skyrider-greatsword",
  "skyrider-sword",
  "skyward-atlas",
  "skyward-blade",
  "skyward-harp",
  "skyward-pride",
  "skyward-spine",
  "slingshot",
  "snow-tombed-starsilver",
  "solar-pearl",
  "song-of-broken-pines",
  "staff-of-homa",
  "summit-shaper",
  "sword-of-descension",
  "the-alley-flash",
  "the-bell",
  "the-black-sword",
  "the-catch",
  "the-flute",
  "the-stringless",
  "the-unforged",
  "the-viridescent-hunt",
  "the-widsith",
  "thrilling-tales-of-dragon-slayers",
  "thundering-pulse",
  "traveler-s-handy-sword",
  "twin-nephrite",
  "vortex-vanquisher",
  "waster-greatsword",
  "white-iron-greatsword",
  "white-tassel",
  "whiteblind",
  "windblume-ode",
  "wine-and-song",
  "wolf-s-gravestone",
];

const weaponMap = {
  "alley-hunter": {
    id: "alley_hunter",
    name: "暗巷猎手",
    type: "Bow",
    rarity: 4,
    baseAttack: 41,
    subStat: "Attack",
    passiveName: "Urban Guerrilla",
    passiveDesc:
      "Every 4s a character is on the field, their ATK increases by 4/5/6/7/8% and their CRIT DMG increases by 4/5/6/7/8%. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.",
    location: "Gacha",
  },
  "amos-bow": {
    id: "amos_bow",
    name: "阿莫斯之弓",
    type: "Bow",
    rarity: 5,
    baseAttack: 46,
    subStat: "ATK",
    passiveName: "Strong-Willed",
    passiveDesc:
      "Increases Normal Attack and Aimed Shot DMG by 12/15/18/21/24%. Increases DMG from arrows shot by a further 8/10/12/14/16% for every 0.1s that the arrow is in flight, up to 0.5s. Stacks up to 5 times on each arrow.",
    location: "Gacha",
  },
  "aquila-favonia": {
    id: "aquila_favonia",
    name: "风鹰剑",
    type: "Sword",
    rarity: 5,
    baseAttack: 48,
    subStat: "Physical DMG Bonus",
    passiveName: "Falcon's Defiance",
    passiveDesc:
      "ATK is increased by 20/25/30/35/40%. Triggers on taking DMG: the soul of the Falcon of the West awakens, holding the banner of the resistance aloft, regenerating HP equal to 100/115/130/145/160% of ATK and dealing 200/230/260/290/320% of ATK as DMG to surrounding enemies. This effect can only occur once every 15s.",
    location: "Gacha",
  },
  "black-tassel": {
    id: "black_tassel",
    name: "黑缨枪",
    type: "Polearm",
    rarity: 3,
    baseAttack: 38,
    subStat: "HP",
    passiveName: "Bane of the Soft",
    passiveDesc: "Increases DMG against slimes by 40/50/60/70/80%.",
    location: "Gacha",
  },
  "blackcliff-amulet": {
    id: "blackcliff_amulet",
    name: "黑岩绯玉",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT DMG",
    passiveName: "Press the Advantage",
    passiveDesc:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    location: "Starglitter Exchange",
  },
  "blackcliff-longsword": {
    id: "blackcliff_longsword",
    name: "黑岩长剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 44,
    subStat: "CRIT DMG",
    passiveName: "Press the Advantage",
    passiveDesc:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    location: "Starglitter Exchange",
  },
  "blackcliff-pole": {
    id: "blackcliff_pole",
    name: "黑岩刺枪",
    type: "Polearm",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT DMG",
    passiveName: "Press the Advantage",
    passiveDesc:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    location: "Starglitter Exchange",
  },
  "blackcliff-slasher": {
    id: "blackcliff_slasher",
    name: "黑岩斩刀",
    type: "Claymore",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT DMG",
    passiveName: "Press the Advantage",
    passiveDesc:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    location: "Starglitter Exchange",
  },
  "blackcliff-warbow": {
    id: "blackcliff_warbow",
    name: "黑岩战弓",
    type: "Bow",
    rarity: 4,
    baseAttack: 44,
    subStat: "CRIT DMG",
    passiveName: "Press the Advantage",
    passiveDesc:
      "After defeating an enemy, ATK is increased by 12/15/18/21/24% for 30s. This effect has a maximum of 3 stacks, and the duration of each stack is independent of the others.",
    location: "Starglitter Exchange",
  },
  "bloodtainted-greatsword": {
    id: "bloodtainted_greatsword",
    name: "沐浴龙血的剑",
    type: "Claymore",
    rarity: 3,
    baseAttack: 38,
    subStat: "Elemental Mastery",
    passiveName: "Bane of Fire and Thunder",
    passiveDesc: "Increases DMG against enemies affected by Pyro or Electro by 12/15/18/21/24%.",
    location: "Gacha",
  },
  "compound-bow": {
    id: "compound_bow",
    name: "钢轮弓",
    type: "Bow",
    rarity: 4,
    baseAttack: 41,
    subStat: "Physical DMG Bonus",
    passiveName: "Infusion Arrow",
    passiveDesc:
      "Normal Attack and Aimed Shot hits increase ATK by 4/5/6/7/8% and Normal Attack SPD by 1.2/1.5/1.8/2.1/2.4% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
    location: "Crafting",
  },
  "cool-steel": {
    id: "cool_steel",
    name: "冷刃",
    type: "Sword",
    rarity: 3,
    baseAttack: 39,
    subStat: "ATK",
    passiveName: "Bane of Water and Ice",
    passiveDesc: "Increases DMG against enemies affected by Hydro or Cryo by 12/15/18/21/24%.",
    location: "Gacha",
  },
  "crescent-pike": {
    id: "crescent_pike",
    name: "流月针",
    type: "Polearm",
    rarity: 4,
    baseAttack: 44,
    subStat: "Physical DMG Bonus",
    passiveName: "Infusion Needle",
    passiveDesc:
      "After picking up an Elemental Orb/Particle, Normal and Charged Attacks deal an additional 20% ATK as DMG for 5s.",
    location: "Crafting",
  },
  "dark-iron-sword": {
    id: "dark_iron_sword",
    name: "暗铁剑",
    type: "Sword",
    rarity: 3,
    baseAttack: 40,
    subStat: "Elemental Mastery",
    passiveName: "Overloaded",
    passiveDesc:
      "Upon causing an Overloaded, Superconduct, Electro-Charged, or an Electro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
    location: "Talk to Chen the Sharp",
  },
  deathmatch: {
    id: "deathmatch",
    name: "决斗之枪",
    type: "Polearm",
    rarity: 4,
    baseAttack: 41,
    subStat: "CRIT Rate",
    passiveName: "Gladiator",
    passiveDesc:
      "If there are at least 2 opponents nearby, ATK is increased by 16% and DEF is increased by 16%. If there are less than 2 enemies nearby, ATK is increased by 24%.",
    location: "BP Bounty",
  },
  "debate-club": {
    id: "debate_club",
    name: "以理服人",
    type: "Claymore",
    rarity: 3,
    baseAttack: 39,
    subStat: "ATK",
    passiveName: "Blunt Conclusion",
    passiveDesc:
      "After using an Elemental Skill, Normal or Charged Attacks, on hit, deal an additional 60/75/90/105/120% ATK DMG in a small area. Effect lasts 15s. DMG can only occur once every 3s.",
    location: "Gacha",
  },
  "dodoco-tales": {
    id: "dodoco_tales",
    name: "嘟嘟可故事集",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 41,
    subStat: "ATK",
    passiveName: "Dodoventure!",
    passiveDesc:
      "Normal Attack hits on opponents increase Charged Attack DMG by 16% for 6s. Charged Attack hits on opponents increase ATK by 8% for 6s.",
    location: "Event",
  },
  "dragonspine-spear": {
    id: "dragonspine_spear",
    name: "龙脊长枪",
    type: "Polearm",
    rarity: 4,
    baseAttack: 41,
    subStat: "Physical DMG Bonus",
    passiveName: "Frost Burial",
    passiveDesc:
      "Hitting an opponent with Normal and Charged Attacks has a 60/70/80/90/100% chance of forming and dropping an Everfrost Icicle above them, dealing 80/95/110/125/140% AoE ATK DMG.\nOpponents affected by Cryo are dealt 200/240/280/320/360% ATK DMG. Can only occur once every 10s.",
    location: "Crafting",
  },
  "elegy-for-the-end": {
    id: "elegy_for_the_end",
    name: "终末嗟叹之诗",
    type: "Bow",
    rarity: 5,
    baseAttack: 46,
    subStat: "Energy Recharge",
    passiveName: "The Parting Refrain",
    passiveDesc:
      'A part of the "Millennial Movement" that wanders amidst the winds. Increases Elemental Mastery by 60/75/90/105/120. When the Elemental Skills or Elemental Bursts of the character wielding this weapon hit opponents, that character gains a Sigil of Remembrance. This effect can be triggered once every 0.2s and can be triggered even if said character is not on the field. When you possess 4 Sigils of Remembrance, all of them will be consumed and all nearby party members will obtain the "Millennial Movement: Farewell Song" effect for 12s. "Millennial Movement: Farewell Song" increases Elemental Mastery by 100/125/150/175/200 and increases ATK by 20/25/30/35/40%. Once this effect is triggered, you will not gain Sigils of Remembrance for 20s. Of the many effects of the "Millennial Movement," buffs of the same type will not stack.',
    location: "Gacha",
  },
  "emerald-orb": {
    id: "emerald_orb",
    name: "翡玉法球",
    type: "Catalyst",
    rarity: 3,
    baseAttack: 40,
    subStat: "Elemental Mastery",
    passiveName: "Rapids",
    passiveDesc:
      "Upon causing a Vaporize, Electro-Charged, Frozen, or a Hydro-infused Swirl reaction, increases Base ATK by 20/25/30/35/40% for 12s.",
    location: "Gacha",
  },
  "eye-of-perception": {
    id: "eye_of_perception",
    name: "昭心",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 41,
    subStat: "ATK",
    passiveName: "Echo",
    passiveDesc:
      "Normal and Charged Attacks have a 50% chance to fire a Bolt of Perception, dealing 240/270/300/330/360% ATK as DMG. This bolt can bounce between enemies a maximum of 4 times. This effect can occur once every 12/11/10/9/8s.",
    location: "Gacha",
  },
  "favonius-codex": {
    id: "favonius_codex",
    name: "西风秘典",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "Energy Recharge",
    passiveName: "Windfall",
    passiveDesc:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
    location: "Gacha",
  },
  "favonius-greatsword": {
    id: "favonius_greatsword",
    name: "西风大剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 41,
    subStat: "Energy Recharge",
    passiveName: "Windfall",
    passiveDesc:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
    location: "Gacha",
  },
  "favonius-lance": {
    id: "favonius_lance",
    name: "西风长枪",
    type: "Polearm",
    rarity: 4,
    baseAttack: 44,
    subStat: "Energy Recharge",
    passiveName: "Windfall",
    passiveDesc:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
    location: "Gacha",
  },
  "favonius-sword": {
    id: "favonius_sword",
    name: "西风剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 41,
    subStat: "Energy Recharge",
    passiveName: "Windfall",
    passiveDesc:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
    location: "Gacha",
  },
  "favonius-warbow": {
    id: "favonius_warbow",
    name: "西风猎弓",
    type: "Bow",
    rarity: 4,
    baseAttack: 41,
    subStat: "Energy Recharge",
    passiveName: "Windfall",
    passiveDesc:
      "CRIT hits have a 60/70/80/90/100% chance to generate 1 Elemental Orb, which will regenerate 6 Energy for the character. Can only occur once every 12/10.5/9/7.5/6s.",
    location: "Gacha",
  },
  "ferrous-shadow": {
    id: "ferrous_shadow",
    name: "铁影阔剑",
    type: "Claymore",
    rarity: 3,
    baseAttack: 39,
    subStat: "HP",
    passiveName: "Unbending",
    passiveDesc:
      "When HP falls below 70/75/80/85/90%, increases Charged Attack DMG by 30/35/40/45/50%, and Charged Attacks become much harder to interrupt.",
    location: "Gacha",
  },
  "festering-desire": {
    id: "festering_desire",
    name: "腐殖之剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 42,
    subStat: "Energy Recharge",
    passiveName: "",
    passiveDesc: "Increases Elemental Skill DMG by 16/20/24/28/32% and Elemental Skill CRIT Rate by 6/7.5/9/10.5/12%.",
    location: "Story Quest",
  },
  "fillet-blade": {
    id: "fillet_blade",
    name: "吃虎鱼刀",
    type: "Sword",
    rarity: 3,
    baseAttack: 39,
    subStat: "ATK",
    passiveName: "Gash",
    passiveDesc:
      "On hit, has 50% chance to deal 240/280/320/360/400% ATK DMG to a single enemy. Can only occur once every 15/14/13/12/11s.",
    location: "Chests",
  },
  "freedom-sworn": {
    id: "freedom-sworn",
    name: "苍古自由之誓",
    type: "Sword",
    rarity: "5",
    BaseAttack: "46",
    subStat: "Elemental Mastery",
    passiveName: "Revolutionary Chorale",
    passiveDesc:
      'A part of the "Millennial Movement" that wanders amidst the winds. Increases DMG by 10%/12.5%/15%/17.5%/20%. When the character wielding this weapon triggers Elemental Reactions, they gain a Sigil of Rebellion. This effect can be triggered once every 0.5s and can be triggered even if said character is not on the field.When you possess 2 Sigils of Rebellion, all of them will be consumed and all nearby party members will obtain "Millennial Movement: Song of Resistance" for 12s. "Millennial Movement: Song of Resistance" increases Normal, Charged, and Plunging Attack DMG by 16%/20%/24%/28%/32% and increases ATK by 20%/25%/30%/35%/40%. Once this effect is triggered, you will not gain Sigils of Rebellion for 20s.Of the many effects of the "Millennial Movement," buffs of the same type will not stack.',
    location: "Gacha",
  },
  frostbearer: {
    id: "frostbearer",
    name: "忍冬之果",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "",
    passiveDesc:
      "Hitting an opponent with Normal and Charged Attacks has a 60% chance of forming and dropping an Everfrost Icicle above them, dealing 80% AoE ATK DMG. Opponents affected by Cryo are dealt 200% ATK DMG. Can only occur once every 10s.",
    location: "Crafting",
  },
  halberd: {
    id: "halberd",
    name: "钺矛",
    type: "Polearm",
    rarity: 3,
    baseAttack: 40,
    subStat: "ATK",
    passiveName: "Heavy",
    passiveDesc: "Normal Attacks deal an additional 160/200/240/280/320% DMG. Can only occur once every 10s.",
    location: "Chests",
  },
  "harbinger-of-dawn": {
    id: "harbinger_of_dawn",
    name: "黎明神剑",
    type: "Sword",
    rarity: 3,
    baseAttack: 39,
    subStat: "CRIT DMG",
    passiveName: "Vigorous",
    passiveDesc: "When HP is above 90%, increases CRIT Rate by 14/18/22/24/28%.",
    location: "Gacha",
  },
  "iron-sting": {
    id: "iron_sting",
    name: "铁蜂刺",
    type: "Sword",
    rarity: 4,
    baseAttack: 42,
    subStat: "Elemental Mastery",
    passiveName: "Infusion Stinger",
    passiveDesc: "Dealing Elemental DMG increases all DMG by 6% for 6s. Max 2 stacks. Can only occur once every 1s.",
    location: "Crafting",
  },
  "kaguras-verity": { id: "kaguras-verity", name: "神乐之真意", weaponType: "catalyst" },
  "kitain-cross-spear": {
    id: "kitain_cross_spear",
    name: "喜多院十文字",
    type: "Polearm",
    rarity: 4,
    baseAttack: 44,
    subStat: "Elemental Mastery",
    passiveName: "Samurai Conduct",
    passiveDesc:
      "Increases Elemental Skill DMG by 6/7.5/9/10.5/12%. After Elemental Skill hits an opponent, the character loses 3 Energy but regenerates 3/3.5/4/4.5/5 Energy every 2s for the next 6s. This effect can occur once every 10s. Can be triggered even when the character is not on the field.",
    location: "Crafting",
  },
  "lithic-blade": {
    id: "lithic_blade",
    name: "千岩古剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 41,
    subStat: "CRIT DMG",
    passiveName: "Lithic Axiom - Unity",
    passiveDesc:
      "For every character in the party who hails from Liyue, the character who equips this weapon gains 6/7/8/9/10% ATK increase and 2/3/4/5/6% CRIT Rate increase.",
    location: "Gacha",
  },
  "lithic-spear": {
    id: "lithic_spear",
    name: "千岩长枪",
    type: "Polearm",
    rarity: 4,
    baseAttack: 42,
    subStat: "Physical DMG Bonus",
    passiveName: "Lithic Axiom - Subjugating Evil",
    passiveDesc: "-",
    location: "Gacha",
  },
  "lost-prayer-to-the-sacred-winds": {
    id: "lost_prayer_to_the_sacred_winds",
    name: "四风原典",
    type: "Catalyst",
    rarity: 5,
    baseAttack: 44,
    subStat: "CRIT Rate",
    passiveName: "Boundless Blessing",
    passiveDesc:
      "Increases Movement SPD by 10%. When in battle, earn a 6/8/10/12/14% Elemental DMG Bonus every 4s. Max 4 stacks. Lasts until the character falls or leaves combat.",
    location: "Gacha",
  },
  "luxurious-sea-lord": {
    id: "luxurious_sea_lord",
    name: "衔珠海皇",
    type: "Claymore",
    rarity: 4,
    baseAttack: 41,
    subStat: "ATK",
    passiveName: "Oceanic Victory",
    passiveDesc:
      "Increases Elemental Burst DMG by 12/15/18/21/24%. When Elemental Burst hits opponents, there is a 100/125/150/175/200% chance of summoning a titanic tuna that charges and deals 100% ATK as AoE DMG. This effect can occur once every 15s.",
    location: "Moonlight Merriment Event",
  },
  "magic-guide": {
    id: "magic_guide",
    name: "魔导绪论",
    type: "Catalyst",
    rarity: 3,
    baseAttack: 38,
    subStat: "Elemental Mastery",
    passiveName: "Bane of Storm and Tide",
    passiveDesc: "Increases DMG against enemies affected by Hydro or Electro by 12/15/18/21/24%.",
    location: "Gacha",
  },
  "mappa-mare": {
    id: "mappa_mare",
    name: "万国诸海图谱",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 44,
    subStat: "Elemental Mastery",
    passiveName: "Infusion Scroll",
    passiveDesc: "Triggering an Elemental reaction grants a 8/10/12/14/16% Elemental DMG Bonus for 10s. Max 2 stacks.",
    location: "Crafting",
  },
  "memory-of-dust": {
    id: "memory_of_dust",
    name: "尘世之锁",
    type: "Catalyst",
    rarity: 5,
    baseAttack: 46,
    subStat: "ATK",
    passiveName: "Golden Majesty",
    passiveDesc:
      "Increase Shield Strength by 20/25/30/35/40%. Scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
    location: "Gacha",
  },
  messenger: {
    id: "messenger",
    name: "信使",
    type: "Bow",
    rarity: 3,
    baseAttack: 40,
    subStat: "CRIT DMG",
    passiveName: "Archer's Message",
    passiveDesc:
      "Aimed Shot hits on weak spots deal an additional 100/125/150/175/200% ATK DMG as CRIT DMG. Can only occur once every 10s.",
    location: "Chest",
  },
  "mitternachts-waltz": {
    id: "mitternachts_waltz",
    name: "幽夜华尔兹",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "Physical DMG Bonus",
    passiveName: "Evernight Duet",
    passiveDesc:
      "Normal Attack hits on opponents increase Elemental Skill DMG by 20% for 5s. Elemental Skill hits on opponents increase Normal Attack DMG by 20% for 5s.",
    location: "Gacha",
  },
  "otherworldly-story": {
    id: "otherworldly_story",
    name: "异世界行记",
    type: "Catalyst",
    rarity: 3,
    baseAttack: 39,
    subStat: "Energy Recharge",
    passiveName: "Energy Shower",
    passiveDesc: "Each Elemental Orb or Particle collected restores 1/1.25/1.5/1.75/2% HP.",
    location: "Chests",
  },
  predator: {
    id: "predator",
    name: "掠食者",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "Strong Strike",
    passiveDesc:
      "Dealing Cryo DMG to opponents increases this character's Normal and Charged Attack DMG by 10% for 6s. This effect can have a maximum of 2 stacks. Additionally, when Aloy equips Predator, ATK is increased by 66.",
    location: "Play Station Event",
  },
  "primordial-jade-cutter": {
    id: "primordial_jade_cutter",
    name: "磐岩结绿",
    type: "Sword",
    rarity: "5",
    BaseAttack: "44",
    subStat: "CRIT Rate",
    passiveName: "Protector's Virtue",
    passiveDesc:
      "HP increased by 20%/25%/30%/35%/40%. Additionally, provides an ATK Bonus based on 1.2%/1.5%/1.8%/2.1%/2.4% of the wielder's Max HP.",
    location: "Gacha",
  },
  "primordial-jade-winged-spear": {
    id: "primordial_jade_winged_spear",
    name: "和璞鸢",
    type: "Polearm",
    rarity: 5,
    baseAttack: 48,
    subStat: "CRIT Rate",
    passiveName: "Eagle Spear of Justice",
    passiveDesc:
      "On hit, increases ATK by 3.2/3.9/4.6/5.3/6% for 6s. Max 7 stacks. Can only occur once every 0.3s. Full stacks increase Skill DMG by 12/16/20/24/28%.",
    location: "Gacha",
  },
  "prototype-crescent": {
    id: "prototype_crescent",
    name: "试作澹月",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "Unreturning",
    passiveDesc: "Aimed Shot hits on weak points increase Movement SPD by 10% and ATK by 6% for 10s.",
    location: "Crafting",
  },
  "prototype-grudge": {
    id: "prototype_grudge",
    name: "试作星镰",
    type: "Polearm",
    rarity: 4,
    baseAttack: 42,
    subStat: "Energy Recharge",
    passiveName: "Magic Affinity",
    passiveDesc: "After using an Elemental Skill, increases Normal and Charged Attack DMG by 8% for 12s. Max 2 stacks.",
    location: "Crafting",
  },
  "prototype-malice": {
    id: "prototype_malice",
    name: "试作金珀",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "HP",
    passiveName: "Gilding",
    passiveDesc:
      "Using an Elemental Burst regenerates 4/4.5/5/5.5/6 Energy every 2s for 6s. Additionally, all party members will regenerate 4/4.5/5/5.5/6% HP every 2s for this duration.",
    location: "Crafting",
  },
  "prototype-rancour": {
    id: "prototype_rancour",
    name: "试作斩岩",
    type: "Sword",
    rarity: 4,
    baseAttack: 44,
    subStat: "Physical DMG Bonus",
    passiveName: "Smashed Stone",
    passiveDesc:
      "On hit, Normal or Charged Attacks increase Base ATK and DEF by 4/4.5/5/5.5/6% for 6s. Max 4 stacks. Can only occur once every 0.3s.",
    location: "Crafting",
  },
  rainslasher: {
    id: "rainslasher",
    name: "雨裁",
    type: "Claymore",
    rarity: 4,
    baseAttack: 42,
    subStat: "Elemental Mastery",
    passiveName: "Bane of Storm and Tide",
    passiveDesc: "Increases DMG against enemies affected by Hydro or Electro by 20/25/30/35/40%.",
    location: "Gacha",
  },
  "raven-bow": {
    id: "raven_bow",
    name: "鸦羽弓",
    type: "Bow",
    rarity: 3,
    baseAttack: 40,
    subStat: "Elemental Mastery",
    passiveName: "Bane of Flame and Water",
    passiveDesc: "Increases DMG against enemies affected by Hydro or Pyro by 12/15/18/21/24%.",
    location: "Gacha",
  },
  "recurve-bow": {
    id: "recurve_bow",
    name: "反曲弓",
    type: "Bow",
    rarity: 3,
    baseAttack: 38,
    subStat: "HP",
    passiveName: "Cull the Weak",
    passiveDesc: "Defeating an opponent restores 8/10/12/14/16% HP.",
    location: "Chest",
  },
  "royal-bow": {
    id: "royal_bow",
    name: "宗室长弓",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "Focus",
    passiveDesc: "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
    location: "Starglitter Exchange",
  },
  "royal-greatsword": {
    id: "royal_greatsword",
    name: "宗室大剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 43,
    subStat: "ATK",
    passiveName: "Focus",
    passiveDesc: "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
    location: "Starglitter Exchange",
  },
  "royal-grimoire": {
    id: "royal_grimoire",
    name: "宗室秘法录",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 44,
    subStat: "ATK",
    passiveName: "Focus",
    passiveDesc: "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
    location: "Starglitter Exchange",
  },
  "royal-longsword": {
    id: "royal_longsword",
    name: "宗室长剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "Focus",
    passiveDesc: "Upon damaging an enemy, increases CRIT Rate by 8%. Max 5 stacks. A CRIT hit removes all stacks.",
    location: "Starglitter Exchange",
  },
  "royal-spear": {
    id: "royal_spear",
    name: "宗室猎枪",
    type: "Polearm",
    rarity: 4,
    baseAttack: 44,
    subStat: "ATK",
    passiveName: "Focus",
    passiveDesc: "Upon damaging an opponent, increases CRIT Rate by 8%. Max 5 stacks. A CRIT Hit removes all stacks.",
    location: "Starglitter Exchange",
  },
  rust: {
    id: "rust",
    name: "弓藏",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "Rapid Firing",
    passiveDesc: "Increases Normal Attack DMG by 40/50/60/70/80% but decreases Aimed Shot DMG by 8/9/10/11/12%",
    location: "Gacha",
  },
  "sacrificial-bow": {
    id: "sacrificial_bow",
    name: "祭礼弓",
    type: "Bow",
    rarity: 4,
    baseAttack: 44,
    subStat: "Energy Recharge",
    passiveName: "Composed",
    passiveDesc:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
    location: "Gacha",
  },
  "sacrificial-fragments": {
    id: "sacrificial_fragments",
    name: "祭礼残章",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 41,
    subStat: "Elemental Mastery",
    passiveName: "Composed",
    passiveDesc:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
    location: "Gacha",
  },
  "sacrificial-greatsword": {
    id: "sacrificial_greatsword",
    name: "祭礼大剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 44,
    subStat: "Energy Recharge",
    passiveName: "Composed",
    passiveDesc:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
    location: "Gacha",
  },
  "sacrificial-sword": {
    id: "sacrificial_sword",
    name: "祭礼剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 41,
    subStat: "Energy Recharge",
    passiveName: "Composed",
    passiveDesc:
      "After damaging an opponent with an Elemental Skill, the skill has a 40/50/60/70/80% chance to end its own CD. Can only occur once every 30/26/22/18/14s.",
    location: "Gacha",
  },
  "serpent-spine": {
    id: "serpent_spine",
    name: "螭骨剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT Rate",
    passiveName: "Wavesplitter",
    passiveDesc:
      "Every 4s a character is on the field, they will deal 6% more DMG and take 3% more DMG. This effect has a maximum of 5 stacks and will not be reset if the character leaves the field, but will be cleared when the character takes DMG.",
    location: "BP Bounty",
  },
  "skyrider-greatsword": {
    id: "skyrider_greatsword",
    name: "飞天大御剑",
    type: "Claymore",
    rarity: 3,
    baseAttack: 39,
    subStat: "Physical DMG Bonus",
    passiveName: "Courage",
    passiveDesc:
      "On hit, Normal or Charged Attacks increase ATK by 6/7/8/9/10% for 6s. Max 4 stacks. Can only occur once every 0.5s.",
    location: "Stuck inside a stone in Guyun Stone Forest",
  },
  "skyrider-sword": {
    id: "skyrider_sword",
    name: "飞天御剑",
    type: "Sword",
    rarity: 3,
    baseAttack: 38,
    subStat: "Energy Recharge",
    passiveName: "Determination",
    passiveDesc: "Using an Elemental Burst grants a 12/15/18/21/24% increase in ATK and Movement SPD for 12s.",
    location: "Gacha",
  },
  "skyward-atlas": {
    id: "skyward_atlas",
    name: "天空之卷",
    type: "Catalyst",
    rarity: 5,
    baseAttack: 45,
    subStat: "ATK",
    passiveName: "Wandering Clouds",
    passiveDesc:
      "Increases Elemental DMG Bonus by 12/15/18/21/24%. Normal Attack hits have a 50% chance to earn the favor of the clouds. which actively seek out nearby enemies to attack for 15s, dealing 160/200/240/280/320% ATK DMG. Can only occur once every 30s.",
    location: "Gacha",
  },
  "skyward-blade": {
    id: "skyward_blade",
    name: "天空之刃",
    type: "Sword",
    rarity: 5,
    baseAttack: 44,
    subStat: "Energy Recharge",
    passiveName: "Sky-Piercing Fang",
    passiveDesc:
      "CRIT Rate increased by 4%. Gains Skypiercing Might upon using an Elemental Burst:\nIncreases Movement SPD by 10%, increases ATK SPD by 10%, and increases the DMG of Normal and Charged Attack hits by 20% for 12s.",
    location: "Gacha",
  },
  "skyward-harp": {
    id: "skyward_harp",
    name: "天空之翼",
    type: "Bow",
    rarity: 5,
    baseAttack: 45,
    subStat: "CRIT Rate",
    passiveName: "Echoing Ballad",
    passiveDesc:
      "Increases CRIT DMG by 20/25/30/35/40%. Hits have a 60/70/80/90/100% chance to inflict a small AoE attack, dealing 100% Physical ATK DMG. Can only occur once every 4s.",
    location: "Gacha",
  },
  "skyward-pride": {
    id: "skyward_pride",
    name: "天空之傲",
    type: "Claymore",
    rarity: 5,
    baseAttack: 45,
    subStat: "Energy Recharge",
    passiveName: "Sky-Ripping Dragon Spine",
    passiveDesc:
      "Increases all DMG by 8/10/12/14/16%. After using an Elemental Burst, Normal or Charged Attack, on hit, creates a vacuum blade that does 80/100/120/140/160% Physical DMG to enemies along its path. Lasts for 20s or 8 vacuum blades.",
    location: "Gacha",
  },
  "skyward-spine": {
    id: "skyward_spine",
    name: "天空之脊",
    type: "Polearm",
    rarity: 5,
    baseAttack: 48,
    subStat: "Energy Recharge",
    passiveName: "Black Wing",
    passiveDesc:
      "Increases CRIT Rate by 8% and increases Normal ATK SPD by 12%. Additionally, Normal and Charged Attacks hits on enemies have a 50% chance to trigger a vacuum blade that deals 40% of ATK as DMG in a small AoE. This effect can occur no more than once every 2s.",
    location: "Gacha",
  },
  slingshot: {
    id: "slingshot",
    name: "弹弓",
    type: "Bow",
    rarity: 3,
    baseAttack: 38,
    subStat: "CRIT Rate",
    passiveName: "Slingshot",
    passiveDesc:
      "If a Normal Attack or Aimed Shot hits a target within 0.3s of being fired, increases DMG by 36/42/48/54/60%; otherwise, it decreases DMG by 10%.",
    location: "Gacha",
  },
  "solar-pearl": {
    id: "solar_pearl",
    name: "匣里日月",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT Rate",
    passiveName: "Solar Shine",
    passiveDesc:
      "Normal Attack hits increase Elemental Skill and Elemental Burst DMG by 20/25/30/35/40% for 6s. Likewise, Elemental Skill or Elemental Burst hits increase Normal Attack DMG by 20/25/30/35/40% for 6s.",
    location: "BP Bounty",
  },
  "song-of-broken-pines": {
    id: "song_of_broken_pines",
    name: "松籁响起之时",
    type: "Claymore",
    rarity: 5,
    baseAttack: 49,
    subStat: "Physical DMG Bonus",
    passiveName: "Rebel's Banner-Hymn",
    passiveDesc:
      'A part of the "Millennial Movement" that wanders amidst the winds. Increases ATK by 16%, and when Normal or Charged Attacks hit opponents, the character gains a Sigil of Whispers. This effect can be triggered once every 0.3s. When you possess 4 Sigils of Whispers, all of them will be consumed and all nearby party members will obtain the "Millennial Movement: Banner-Hymn" effect for 12s. "Millennial Movement: Banner-Hymn" increases Normal ATK SPD by 12% and increases ATK by 20%. Once this effect is triggered, you will not gain Sigils of Whispers for 20s. Of the many effects of the "Millennial Movement," buffs of the same type will not stack.',
    location: "Gacha",
  },
  "staff-of-homa": {
    id: "staff_of_homa",
    name: "护摩之杖",
    type: "Polearm",
    rarity: 5,
    baseAttack: 46,
    subStat: "CRIT DMG",
    passiveName: "Reckless Cinnabar",
    passiveDesc:
      "HP increased by 20/25/30/35/40%. Additionally, provides an ATK Bonus based on 0.8/1/1.2/1.4/1.6% of the wielder's Max HP. When the wielder's HP is less than 50%, this ATK Bonus is increased by an additional 1/1.2/1.4/1.6/1.8% of Max HP.",
    location: "Gacha",
  },
  "summit-shaper": {
    id: "summit_shaper",
    name: "斫峰之刃",
    type: "Sword",
    rarity: 5,
    baseAttack: 46,
    subStat: "ATK",
    passiveName: "",
    passiveDesc:
      "Increases Shield Strength by 20/25/30/35/40%. Scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield, this ATK increase effect is increased by 100%.",
    location: "Gacha",
  },
  "sword-of-descension": {
    id: "sword_of_descension",
    name: "降临之剑",
    type: "Sword",
    rarity: "4",
    BaseAttack: "39",
    subStat: "ATK",
    passiveName: "Descension",
    passiveDesc:
      "Hitting enemies with Normal or Charged Attacks grants a 50% chance to deal 200% ATK as DMG in a small AoE. This effect can only occur once every 10s. Additionally, if the Traveler equips the Sword of Descension, their ATK is increased by 66.",
    location: "Event",
  },
  "the-alley-flash": {
    id: "the_alley_flash",
    name: "暗巷闪光",
    type: "Sword",
    rarity: 4,
    baseAttack: 44,
    subStat: "CRIT Rate",
    passiveName: "Itinerant Hero",
    passiveDesc: "Continuosly sprinting for at least 1s increases ATK by 28% for 6s. This effect cannot stack.",
    location: "Gacha",
  },
  "the-bell": {
    id: "the_bell",
    name: "钟剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 42,
    subStat: "HP",
    passiveName: "Rebellious Guardian",
    passiveDesc:
      "Taking DMG generates a shield which absorbs DMG up to 20/23/26/29/32% of Max HP. This shield lasts for 10s or until broken, and can only be triggered once every 45s. While protected by the shield, the character gains 12/15/18/21/24% increased DMG.",
    location: "Gacha",
  },
  "the-black-sword": {
    id: "the_black_sword",
    name: "黑剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT Rate",
    passiveName: "Justice",
    passiveDesc:
      "Increases DMG dealt by Normal and Charged Attacks by 20%.\nAdditionally, regenerates 60% of ATK as HP when Normal and Charged Attacks score a CRIT Hit. This effect can occur once every 5s.",
    location: "BP Bounty",
  },
  "the-catch": {
    id: "the_catch",
    name: "「渔获」",
    type: "Polearm",
    rarity: 4,
    baseAttack: 42,
    subStat: "Energy Recharge",
    passiveName: "Shanty",
    passiveDesc: "Increases Elemental Burst DMG by 16/20/24/28/32% and Elemental Burst CRIT Rate by 6/7.5/9/10.5/12%.",
    location: "Inazuma Fishing Association",
  },
  "the-flute": {
    id: "the_flute",
    name: "笛剑",
    type: "Sword",
    rarity: 4,
    baseAttack: 42,
    subStat: "ATK",
    passiveName: "Chord",
    passiveDesc:
      "Normal or Charged Attacks grant Harmonic on hits. Gaining 5 Harmonics triggers the power of music and deals 100/125/150/175/200% ATK DMG to surrounding enemies. Harmonics last up to 30s, and a maximum of 1 can be gained every 0.5s.",
    location: "Gacha",
  },
  "the-stringless": {
    id: "the_stringless",
    name: "绝弦",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "Elemental Mastery",
    passiveName: "Arrowless Song",
    passiveDesc: "Increases Elemental Skill and Elemental Burst DMG by 24/30/36/42/48%.",
    location: "Gacha",
  },
  "the-unforged": {
    id: "the_unforged",
    name: "无工之剑",
    type: "Claymore",
    rarity: 5,
    baseAttack: 46,
    subStat: "ATK",
    passiveName: "Golden Majesty",
    passiveDesc:
      "Increases Shield Strength by 20/25/30/35/40%, scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%",
    location: "Gacha",
  },
  "the-viridescent-hunt": {
    id: "the_viridescent_hunt",
    name: "苍翠猎弓",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT Rate",
    passiveName: "Verdant Wind",
    passiveDesc:
      "Upon hit, Normal and Aimed Shot Attacks have a 50% chance to generate a Cyclone, which will continuously attract surrounding enemies, dealing 40% of ATK as DMG to these enemies every 0.5s for 4s. This effect can only occur once every 14s.",
    location: "BP Bounty",
  },
  "the-widsith": {
    id: "the_widsith",
    name: "流浪乐章",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "CRIT DMG",
    passiveName: "Debut",
    passiveDesc:
      "When the character takes the field, they gain a random theme song for 10s:\nRecitative: Increases Base ATK by 60%\nInterlude: Elemental Mastery is increased by 240\nAria: Increases all Elemental DMG by 48%\nCan only occur once every 30s",
    location: "Gacha",
  },
  "thrilling-tales-of-dragon-slayers": {
    id: "thrilling_tales_of_dragon_slayers",
    name: "讨龙英杰谭",
    type: "Catalyst",
    rarity: 3,
    baseAttack: 39,
    subStat: "HP",
    passiveName: "Legacy",
    passiveDesc:
      "When switching characters, the new character taking the field has their ATK increased by 24/30/36/42/48% for 10s. This effect can only occur once every 20s.",
    location: "Gacha",
  },
  "thundering-pulse": {
    id: "thundering_pulse",
    name: "飞雷之弦振",
    type: "Bow",
    rarity: 5,
    baseAttack: 46,
    subStat: "CRIT DMG",
    passiveName: "Rule By Thunder",
    passiveDesc:
      "Increases ATK by 20/25/30/35/40% and grants the might of the Thunder Emblem. At stack levels 1/2/3, the Thunder Emblem increases Normal Attack DMG by 12/24/40% // 15/30/50% // 18/36/60% // 21/42/70% // 24/48/80%. The character will obtain 1 stack of Thunder Emblem in each of the following scenarios: Normal Attack deals DMG (stack lasts 5s), casting Elemental Skill (stack lasts 10s); Energy is less than 100% (stack disappears when Energy is full). Each stack's duration is calculated independently.",
    location: "Gacha",
  },
  "twin-nephrite": {
    id: "twin_nephrite",
    name: "甲级宝珏",
    type: "Catalyst",
    rarity: 3,
    baseAttack: 40,
    subStat: "CRIT Rate",
    passiveName: "Guerilla Tactic",
    passiveDesc: "Defeating an enemy increases Movement SPD and ATK by 12/14/16/18/20% for 15s.",
    location: "Chests",
  },
  "vortex-vanquisher": {
    id: "vortex_vanquisher",
    name: "贯虹之槊",
    type: "Polearm",
    rarity: 5,
    baseAttack: 46,
    subStat: "ATK",
    passiveName: "Golden Majesty",
    passiveDesc:
      "Increases Shield Strength by 20/25/30/35/40%, scoring hits on opponents increases ATK by 4/5/6/7/8% for 8s. Max 5 stacks. Can only occur once every 0.3s. While protected by a shield this ATK increase effect is increased by 100%",
    location: "Gacha",
  },
  "white-iron-greatsword": {
    id: "white_iron_greatsword",
    name: "白铁大剑",
    type: "Claymore",
    rarity: 3,
    baseAttack: 39,
    subStat: "DEF",
    passiveName: "Cull the Weak",
    passiveDesc: "Defeating an opponent restores 8/10/12/14/16% HP.",
    location: "Chests",
  },
  "white-tassel": {
    id: "white_tassel",
    name: "白缨枪",
    type: "Polearm",
    rarity: 3,
    baseAttack: 39,
    subStat: "CRIT Rate",
    passiveName: "Sharp",
    passiveDesc: "Increases Normal Attack DMG by 24/30/36/42/48%.",
    location: "Chest",
  },
  whiteblind: {
    id: "whiteblind",
    name: "白影剑",
    type: "Claymore",
    rarity: 4,
    baseAttack: 42,
    subStat: "DEF",
    passiveName: "Infusion Blade",
    passiveDesc:
      "On hit, Normal or Charged Attacks increase Base ATK and DEF by 6/7.5/9/10.5/12% for 6s. Max 4 stacks. Can only occur once every 0.5s.",
    location: "Crafting",
  },
  "windblume-ode": {
    id: "windblume_ode",
    name: "风花之颂",
    type: "Bow",
    rarity: 4,
    baseAttack: 42,
    subStat: "Elemental Mastery",
    passiveName: "Windblume Wish",
    passiveDesc:
      "After using an Elemental Skill, receive a boon from the ancient wish of the Windblume, increasing ATK by 16/20/24/28/32% for 6s.",
    location: "Invitation to Windblume (v1.4) Event Shop",
  },
  "wine-and-song": {
    id: "wine_and_song",
    name: "酒与歌",
    type: "Catalyst",
    rarity: 4,
    baseAttack: 42,
    subStat: "Energy Recharge",
    passiveName: "Wind in the Square",
    passiveDesc:
      "For every character in the party who hails from Mondstadt, the character who equips this weapon gains 8/10/12/14/16% ATK increase and 3/3.5/4/4.5/5% Movement SPD increase.",
    location: "Gacha",
  },
};

export { weaponMap, weapons };
export default weaponMap;
